apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-gke
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
          name: github-actions-gke
          image: github-actions-gke
          ports:
            —containerPort: 8080